Add flysystem-sftp adapter support
Flagbit/Magento2-Flysystem pull request #7
Opened 2018-08-08 15:46 UTC by Perni1984

2018-08-09 12:59 UTC, robin-homberg commented
**basically a very good code style, thank you  :+1:**
There is one bug i found and some small things that could be done better:

Bug:
* If you define the content of the private key in the SFTP Adapter configuration. The form field for the content needs to be a textarea not an input type="text".
An input type="text" does not store line wraps and the provided key wo'nt work.
The form field for the private key needs to be splitted in 2 seperate fields. One to provide a key path and another to provide a key content

Things that could be done better:
* There is a test missing for line 236 of Flagbit\Flysystem\Model\Filesystem\Manager. That means that there isn't anymore a unittest line coverage of 100%. Thats sad :(
* The .idea directory in .gitinore is nothing regarded to the module, but to the development IDE. This should not be commited to the repository.
* I would like to have a comment under the configuration field for "Directory Permissions". To give an example in which format to write the permissions and that 0744 will be set by default if nothing is provided in the configuration.
* There should be some default values for the configuration fields. like port default 22 and a timeout default.

2018-08-10 11:45 UTC, robin-homberg requested changes
**basically a very good code style, thank you**  :+1:
There is one bug i found and some small things that could be done better:

Bug:

- If you define the content of the private key in the SFTP Adapter configuration. The form field for the content needs to be a textarea not an input type="text".
An input type="text" does not store line wraps and the provided key wo'nt work.
The form field for the private key needs to be splitted in 2 seperate fields. One to provide a key path and another to provide a key content

Things that could be done better:

- There is a test missing for line 236 of Flagbit\Flysystem\Model\Filesystem\Manager. That means that there isn't anymore a unittest line coverage of 100%. Thats sad :(
- The .idea directory in .gitinore is nothing regarded to the module, but to the development IDE. This should not be commited to the repository.
- I would like to have a comment under the configuration field for "Directory Permissions". To give an example in which format to write the permissions and that 0744 will be set by default if nothing is provided in the configuration.
- There should be some default values for the configuration fields. like port default 22 and a timeout default.

2018-08-13 10:43 UTC, Perni1984 commented
@robin-homberg changes should be in now

2018-08-13 12:39 UTC, robin-homberg approved these changes

2018-08-13 12:40 UTC, merged